### PR TITLE
fix(build): renamed option key to _option

### LINKED ISSUE #25: Inconsistent Attribute Naming: options instead of _options in NgRspackModuleFederationPlugin
### Description 
I found an inconsistency in the attribute naming for NgRspackModuleFederationPlugin. This plugin returns an attribute named options, while other plugins following the Module Federation standard return _options. This difference breaks compatibility in workflows or tools that depend on the consistent use of _options.

### Expected Behavior
The NgRspackModuleFederationPlugin should return _options to align with the standard naming convention used by other Module Federation plugins, such as RspackModuleFederationPlugin.

### Current Behavior

Currently, NgRspackModuleFederationPlugin returns:

```
MF Entry NgRspackModuleFederationPlugin {
  options: {
    // other attributes
  }
}
```
While other plugins like RspackModuleFederationPlugin return:

```
MF Entry ModuleFederationPlugin {
  _options: {
    // other attributes
  }
}
```
### Suggested Solution
Rename the options attribute in NgRspackModuleFederationPlugin to _options to ensure consistent attribute naming across plugins in compliance with the Module Federation standard.

### Impact
This inconsistency causes issues when using NgRspackModuleFederationPlugin alongside other plugins that rely on the _options attribute.

### PR DESCRIPTION
**Pull request by swalker326**
## Description
This PR updates the NgRspackModuleFederationPlugin to standardize the attribute name from options to _options, aligning it with the naming conventions used in other Module Federation plugins. This change resolves the inconsistency and improves compatibility across plugins.

## Changes
Renamed options to _options throughout the plugin configuration.
Updated all references to use _options instead of options.
This update should improve interoperability for users who rely on a consistent API structure across Module Federation plugins.

Closes #25

### CODE REVIEW

**Comment by zmzlois** [comment]
this awesome, should we dm Column?

File: packages/build/src/lib/plugins/module-federation/ng-rspack-module-federation-plugin.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export class NgRspackModuleFederationPlugin implements RspackPluginInstance {
   private mappedRemotes: MappedRemotes | undefined;
 
   constructor(
-    private options: ModuleFederationConfig,
+    private _options: ModuleFederationConfig,
```
Comment (zmzlois) [inline packages/build/src/lib/plugins/module-federation/ng-rspack-module-federation-plugin.ts:18]: nice

**Review by zmzlois — APPROVED** [review]

**Comment by Coly010** [comment]
If we're doing this for consistency can we also update the other Plugins in the `build` package?
https://github.com/Coly010/ng-rspack-build/blob/main/packages/build/src/lib/plugins/ng-rspack.ts


https://github.com/Coly010/ng-rspack-build/blob/main/packages/build/src/lib/plugins/module-federation/ng-rspack-module-federation-dev-server-plugin.ts

**Review by Coly010 — CHANGES_REQUESTED** [review]
See comment above

**Review by Coly010 — APPROVED** [review]
LGTM! Thanks!!
